apps/page/urls.py
from django.conf.urls import url

from apps.page.views import home, redirect, UserRegister, user_complete_register

urlpatterns = [
    url(r'^$', home, name="home"),
    url(r'^(?P<idiom>[a-z]{2})/$', home, name="home"),
    url(r'^signup/$', UserRegister.as_view(), name="signup"),
    url(r'^(?P<idiom>[a-z]{2})/(?P<pagename>[a-z]{,20})/complete-register$', user_complete_register, name="complete_register"),
    # url(r'^page/(?P<idiom>\w+)/(?P<pagename>\w+)$', redirect, name="redirect"),
    url(r'^(?P<idiom>[a-z]{2})/(?P<pagename>[a-z]{,20})$', redirect, name="redirect"),
]

poicofu/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.page.urls', namespace="page")),

    url(r'^login/', login, {'template_name' : 'user/login.html'}, name="login"),
    url(r'^accounts/login/', login, {'template_name' : 'user/login.html'}, name="login"),
    url(r'^logout/$', logout_then_login, name='logout'),
    url(r'^auth/', include('social_django.urls', namespace='social')),
]

apps/usuario/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import AbstractUser


class Country(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class City(models.Model):
    name = models.CharField(max_length=30)
    country = models.ForeignKey(Country, null=False, blank=False, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Language(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class UserMethods:
    def initial(self):
        return self.username[0].upper()

    def fname(self):
        return '{} {}'.format(self.first_name, self.last_name)


class User(AbstractUser, UserMethods):
	age = models.IntegerField(null=True, blank=True)
	city = models.ForeignKey(City, null=True, blank=True, on_delete=models.CASCADE)
	language = models.ForeignKey(Language, null=True, blank=True, on_delete=models.CASCADE)
	provider = models.CharField(max_length=20, null=True, blank=True)


class Code(models.Model):
    name = models.CharField(max_length=30)
    code = models.BinaryField()
    description = models.CharField(max_length=50)
    compilations = models.IntegerField(default=0)
    creation_date = models.DateField(auto_now=True)
    user = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE)

    def __str__(self):
        return "{}  ({})".format(self.user.username, self.name)

templates/page/community.html
{% extends 'base/base.html' %}
{% load staticfiles %}

{% block title %} {{ language.info.community }} {% endblock %}


{% block content %}
	<div class="container">
		<div class="row">
			<div class="col s12 m10">
				<h3 class="truncate white-text">{{language.community.greeting}} {{user.username}}</h3>
				<p class="flow-text white-text">{{language.community.info}}</p>

				 {% if codes.all %}
					 {% for code in codes.all %}
						 <div class="card-panel z-depth-2 hoverable card-usercode"  style="overflow: hidden;">
							<div class="col s4 m2">
								<img src="https://api.fnkr.net/testimg/200x200/00CED1/FFF/?text={{code.user.initial}}" class="responsive-img circle">
							</div>
							<div class="col s8 m10">
								<div class="right date">{{code.creation_date}}</div>
								<div class="username">{{code.user.first_name}} {{code.user.last_name}} ({{code.user.username}})</div>
								<div class="codename">{{code.name}}</div>
								<div class="description">{{code.description}}</div>
							</div>
						</div>
					 {% endfor %}
				 {% else %}
					 <div class="center">
						 <h4>No se han encontrado aportes de codigos</h4>
					 </div>
				 {% endif %}
			</div>
		</div>
	</div>
{% endblock %}


{% block extrajs %}
	<script type="text/javascript">
		$(document).ready(function(){

            $('select[name=idioms]').change(function(){
                url = "{% url 'page:home' %}"+$(this).val()+"/community";
                console.log(url);
                location.href = url;
            });

            $('body').addClass('teal');

		});
	</script>
{% endblock %}

templates/page/compiler.html
{% extends 'base/base.html' %}
{% load staticfiles %}

{% block title %} {{ language.info.compiler }} {% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col s12 m12">
				<!-- <h3 class="truncate white-text"></h3> -->
				<p class="flow-text white-text">{{language.compiler.info}}</p>
                <div class="card">
                    <div class="card-content">
                        <div class="row">
                           <div class="input-field col s12">
                                <textarea rows="10"></textarea>

                           </div>
                         </div>
                    </div>
                    <div class="card-action grey lighten-3 btn-panel-compiler" style="overflow: hidden;">
                        <a href="#" class="btn waves-effect waves-light blue" id="save_pc" disabled>
                            <i class="fas fa-laptop fa-lg"></i>&nbsp;&nbsp; {{language.compiler.save_pc}}
                        </a>
                        <a href="#" class="btn waves-effect waves-light blue darken-3" id="save_db" disabled>
                            {{language.compiler.save_db}}&nbsp;&nbsp; <i class="fas fa-cloud-upload-alt fa-lg"></i>
                        </a>
                        <div class="right">
                            <a href="#" class="btn waves-effect waves-light green">
                                <i class="fas fa-terminal fa-lg"></i> {{language.compiler.run}}
                            </a>
                        </div>
                    </div>
                </div>
			</div>
            <div class="col s12 m8">
                <div class="card-panel z-depth-3 no-padding card-log">
					<center>{{language.compiler.compilation_log}}</center>
                    <div id="compilation_log">
                    	Lorem ipsum dolor sit amet, consectetur <br>
						adipisicing elit. Ea optio, nisi <br>
						quasi quis facere veritatis ab 	<br>
						suscipit numquam beatae accusamus! <br>
						Omnis ea enim quam fugit amet facilis <br>
						Lorem ipsum dolor sit amet, consectetur <br>
						adipisicing elit. Ea optio, nisi <br>
						quasi quis facere veritatis ab 	<br>
						suscipit numquam beatae accusamus! <br>
						Omnis ea enim quam fugit amet facilis <br>
						Lorem ipsum dolor sit amet, consectetur <br>
						adipisicing elit. Ea optio, nisi <br>
						quasi quis facere veritatis ab 	<br>
						suscipit numquam beatae accusamus! <br>
						Omnis ea enim quam fugit amet facilis <br>
						nam pariatur. Dolorem. Lorem ipsum dolor sit amet,
                    </div>
                </div>
            </div>
			<div class="col s12 m4">
                <div class="card-panel z-depth-3 no-padding card-log">
					<center>{{language.compiler.execution_result}}</center>
                    <div id="compilation_log"></div>
                </div>
            </div>
		</div>
	</div>
{% endblock %}


{% block extrajs %}
	<script type="text/javascript">
		$(document).ready(function(){

            $('select[name=idioms]').change(function(){
                url = "{% url 'page:home' %}"+$(this).val()+"/compiler";
                console.log(url);
                location.href = url;
            });

            $('body').addClass('teal');

		});
	</script>
{% endblock %}

templates/page/home.html
{% extends 'base/base.html' %}
{% load staticfiles %}

{% block title %} {{ language.info.home }} {% endblock %}

{% block content %}

 	{% include 'base/sections/slider.html' %}

    <div class="container">
        <!-- <h4>La pagina se mostrara en {{ language.name }}</h4> -->
        <div class="row">
        	<div class="center">
        		<h4>{{ language.info.greeting }} {{ language.info.name }}</h4>
        	</div>
        	<p class="flow-text">
				{{ language.info.description }}
        	</p>
        </div>
        <div class="row">
        	<div class="center">
        		<h4>{{ language.info.charts }}</h4>
        	</div>
        	<h4>{{ language.info.chart1_title }}</h4>
        	<br>
        	<h4>{{ language.info.chart2_title }}</h4>
        </div>

    </div>
{% endblock %}

{% block extrajs %}
	<script type="text/javascript">
		$(document).ready(function(){

			$('.slider').slider({
				indicators: false
			});

            $('select[name=idioms]').change(function(){
                url = "{% url 'page:home' %}"+$(this).val();
                console.log(url);
                location.href = url;
            });

		});
	</script>
{% endblock %}

templates/page/mycodes.html
{% extends 'base/base.html' %}
{% load staticfiles %}

{% block title %} {{ language.info.community }} {% endblock %}


{% block content %}
	<div class="container">
		<div class="row">
			<div class="col s12 offset-m1 m10">
				<h3 class="truncate white-text">{{language.info.my_codes}}</h3>
                <div class="dashed-divider"></div><br>
				 {% if user.code_set.all %}
					 {% for code in user.code_set.all %}
						 <div class="card-panel z-depth-2 hoverable card-usercode"  style="overflow: hidden;">
							<div class="col s4 m2">
								<img src="https://api.fnkr.net/testimg/200x200/00CED1/FFF/?text={{code.user.initial}}" class="responsive-img circle">
							</div>
							<div class="col s8 m10">
								<div class="right date">{{code.creation_date}}</div>
								<div class="username">{{code.user.first_name}} {{code.user.last_name}} ({{code.user.username}})</div>
								<div class="codename">{{code.name}}</div>
								<div class="description">{{code.description}}</div>
							</div>
						</div>
					 {% endfor %}
				 {% else %}
					 <div class="center">
						 <h4>Aun no tienes ningun código guardado</h4>
					 </div>
				 {% endif %}
			</div>
		</div>
	</div>
{% endblock %}


{% block extrajs %}
	<script type="text/javascript">
		$(document).ready(function(){

            $('select[name=idioms]').change(function(){
                url = "{% url 'page:home' %}"+$(this).val()+"/mycodes";
                console.log(url);
                location.href = url;
            });

            $('body').addClass('teal');

		});
	</script>
{% endblock %}

templates/page/profile.html
{% extends 'base/base.html' %}
{% load staticfiles %}

{% block title %} {{language.info.profile}} {% endblock %}

{% block content %}
    <br>
    <div class="container">
        <div class="row">
            <div class="col offset-s3 s6 m3 ">
                <br>
                <img src="{% static 'images/usericon.png' %}" class="circle responsive-img z-depth-2" alt="usericon">
            </div>
            <div class="col s12 offset-m1 m7">
                <div class="row">
                    <h3 class="greeting">{{language.community.greeting}} {{user.fname}}</h3>
                    <h4>({{user.username}})</h4>
                    <h5>{{user.email}}</h5>
                    <br>
                    <div>
                        <span class="profile-text">{{language.profile.n_codes}}: <b>{{user.code_set.count}}</b></span>
                        <div class="right">
                            <a href="{% url 'page:redirect' language.min_name 'mycodes' %}" class="btn waves-effect waves-light btn-rounded">
                                <i class="fas fa-code"></i> {{language.info.my_codes}}</a>
                        </div>
                    </div>
                </div>
                <div class="dashed-divider"></div>

                <div class="row profile-text">
                    <h5>
                        <b>{{language.profile.personal_data}}</b>
                        <div class="right">
                            <a href="#" class="btn waves-effect waves-light btn-rounded">
                                <i class="fas fa-user-edit fa-lg"></i> {{language.profile.edit}}
                            </a>
                        </div>
                    </h5>
                    <div class="add-padding">
                        <table>
                            <tbody>
                                <tr>
                                    <td><b>{{language.profile.age}}:</b></td>
                                    <td>{{user.age}}</td>
                                </tr>
                                <tr>
                                    <td><b>{{language.profile.city}}:</b></td>
                                    <td>{{user.city}}</td>
                                </tr>
                                <tr>
                                    <td><b>{{language.profile.country}}:</b></td>
                                    <td>{{user.city.country}}</td>
                                </tr>
                                <tr>
                                    <td><b>{{language.profile.language_preference}}:</b></td>
                                    <td>{{user.language.name}}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="dashed-divider"></div>

                <div class="row profile-text">
                    <h5><b>{{language.profile.account_options}}</b></h5>
                    <div class="add-padding">
                        <h6>
                            {{language.profile.change_password}}
                            <div class="right">
                                <a href="#" class="btn waves-effect waves-light btn-rounded blue">
                                    <i class="fas fa-user-shield fa-lg"></i> {{language.profile.change}}
                                </a>
                            </div>
                        </h6>

                        <h6>
                            {{language.profile.delete_account}}
                            <div class="right">
                                <a href="#" class="btn waves-effect waves-light btn-rounded red">
                                    <i class="fas fa-user-slash fa-lg"></i> {{language.profile.delete}}
                                </a>
                            </div>
                        </h6>

                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

{% block extrajs %}
	<script type="text/javascript">
		$(document).ready(function(){

            $('select[name=idioms]').change(function(){
                url = "{% url 'page:home' %}"+$(this).val()+"/profile";
                console.log(url);
                location.href = url;
            });

		});
	</script>
{% endblock %}