apps/page/urls.py
from django.conf.urls import url

from apps.page.views import home, redirect, UserRegister, user_complete_register

urlpatterns = [
    url(r'^$', home, name="home"),
    url(r'^(?P<idiom>[a-z]{2})/$', home, name="home"),
    url(r'^signup/$', UserRegister.as_view(), name="signup"),
    url(r'^(?P<idiom>[a-z]{2})/(?P<pagename>[a-z]{,20})/complete-register$', user_complete_register, name="complete_register"),
    # url(r'^page/(?P<idiom>\w+)/(?P<pagename>\w+)$', redirect, name="redirect"),
    url(r'^(?P<idiom>[a-z]{2})/(?P<pagename>[a-z]{,20})$', redirect, name="redirect"),
]

poicofu/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.page.urls', namespace="page")),

    url(r'^login/', login, {'template_name' : 'user/login.html'}, name="login"),
    url(r'^accounts/login/', login, {'template_name' : 'user/login.html'}, name="login"),
    url(r'^logout/$', logout_then_login, name='logout'),
    url(r'^auth/', include('social_django.urls', namespace='social')),
]

templates/base/sections/footer.html
<footer class="page-footer teal darken-1">
	<div class="container">
		<div class="row center-align">
			<div class="col s12"><h4>Developers</h4></div>
			<div class="col s12 m6">
				<a href="https://github.com/Fabcore" class="white-text">
					<i class="fab fa-github fa-2x"></i> <big>Fabian Martinez</big>
				</a>
			</div>
			<div class="col s12 m6">
				<a href="https://github.com/samir04m" class="white-text">
					<i class="fab fa-github fa-2x"></i> <big>Samir Mejia</big>
				</a>
			</div>
		</div>
	</div>
	<div class="footer-copyright white-text">
		<div class="container">
			All Rights Reserved © 2018 
			<a class="grey-text text-lighten-4 right" href="http://materializecss.com/">Power By MaterializeCss</a>
		</div>
	</div>
	
</footer>

templates/base/sections/header.html
{% load staticfiles %}
<header>

	<ul id="drop-account" class="dropdown-content">
	  <li><a href="{% url 'page:redirect' language.min_name 'profile' %}"><i class="fas fa-user-tie fa-lg"></i> &nbsp;&nbsp;{{language.info.profile}}</a></li>
	  <!-- <li class="divider"></li> -->
	   <li><a href="{% url 'page:redirect' language.min_name 'mycodes' %}"><i class="fas fa-code fa-lg"></i> &nbsp;&nbsp;{{language.info.my_codes}}</a></li>
	  <li class="divider"></li>
	  <li><a href="{% url 'logout' %}"><i class="fas fa-sign-out-alt fa-lg"></i> &nbsp;&nbsp;{{language.info.logout}}</a></li>
	</ul>

	<nav>
	    <div class="nav-wrapper teal">
	      	<div class="container">
	      		<ul class="left hide-on-med-and-down">
	        		<li>
	        			{% include 'base/modules/select_languages.html' %}
	        		</li>
	      		</ul>
	      		<a href="{% url 'page:redirect' language.min_name '' %}" class="brand-logo truncate" style="margin-left: 20px;"><i class="fab fa-staylinked"></i> POICOFU</a>

				<a href="#" data-activates="mobile" class="button-collapse">
					<i class="fas fa-bars fa-lg"></i>
				</a>

	      		<ul class="right hide-on-med-and-down">
		        	<li><a href="{% url 'page:redirect' language.min_name '' %}">{{language.info.home}}</a></li>

		        	{% if request.user.is_authenticated %}
						<li><a href="{% url 'page:redirect' language.min_name 'community' %}">{{language.info.community}}</a></li>
						<li><a href="{% url 'page:redirect' language.min_name 'compiler' %}">{{language.info.compiler}}</a></li>

						<li><a href="#!" class="dropdown-button" data-activates="drop-account">
							<i class="fas fa-user-astronaut fa-lg"></i>
							{{request.user.username }} <i class="fas fa-angle-down"></i>
						</a></li>
		        	{% else %}
						<li><a href="{% url 'page:signup' %}">{{language.info.sign_up}}</a></li>
						<li><a href="{% url 'login' %}">{{language.info.login}}</a></li>
		        	{% endif %}
	      		</ul>
	      		<ul class="side-nav" id="mobile">
		        	<li><a href="{% url 'page:home' %}">{{language.info.home}}</a></li>
		        	{% if request.user.is_authenticated %}
						<li><a href="{% url 'page:redirect' language.min_name 'community' %}">{{language.info.community}}</a></li>
						<li><a href="{% url 'page:redirect' language.min_name 'compiler' %}">{{language.info.compiler}}</a></li>

						</a></li>
		        	{% else %}
						<li><a href="{% url 'page:signup' %}">{{language.info.sign_up}}</a></li>
						<li><a href="{% url 'login' %}">{{language.info.login}}</a></li>
		        	{% endif %}

	      		</ul>
	      	</div>
	    </div>
	</nav>
</header>

templates/base/sections/slider.html
{% load staticfiles %}
<div class="slider">
    <ul class="slides">
        <li>
            <img src="https://lorempixel.com/580/250/nature/1"> <!-- random image -->
            <div class="caption center-align">
                <h3>{{ language.info.name }}</h3>
                  <h4 class="light grey-text text-lighten-3" id="min_info">
                    {% if request.user.is_authenticated %}
                      {{ language.community.greeting }} {{user.username}}
                    {% else %}
                      {{ language.info.min_info }}
                    {% endif %}
                  </h4>
            </div>
        </li>
       <!--  <li>
            <img src="https://lorempixel.com/580/250/nature/2"> 
            <div class="caption left-align">
              <h3>Left Aligned Caption</h3>
              <h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
            </div>
        </li>
        <li>
            <img src="https://lorempixel.com/580/250/nature/3">
            <div class="caption right-align">
              <h3>Right Aligned Caption</h3>
              <h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
            </div>
        </li> -->
    </ul>
  </div>